name: cat-learn-auto-eeg
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - scikit-learn
  - statsmodels
  - joblib
  - pytest
  - mne
  - threadpoolctl
  - pymc
  - arviz
  - pip
  - pip:
      - autoreject
      - pyprep
      - psychopy
